"""Modulo academico inicial

Revision ID: f7ee31cab09e
Revises: 
Create Date: 2025-11-21 13:04:38.575822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7ee31cab09e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_created_at'))
        batch_op.drop_index(batch_op.f('idx_log_level'))
        batch_op.drop_index(batch_op.f('idx_module'))
        batch_op.drop_index(batch_op.f('idx_user_id'))

    op.drop_table('system_logs')
    with op.batch_alter_table('ai_interactions', schema=None) as batch_op:
        batch_op.alter_column('prompt_text',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('response_text',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_ai_service'))
        batch_op.drop_index(batch_op.f('idx_created_at'))
        batch_op.drop_index(batch_op.f('idx_interaction_type'))
        batch_op.drop_index(batch_op.f('idx_user_id'))
        batch_op.create_index(batch_op.f('ix_ai_interactions_ai_service'), ['ai_service'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_interactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_interactions_interaction_type'), ['interaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_interactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('attention_metrics', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_session_id'))
        batch_op.create_index(batch_op.f('ix_attention_metrics_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('audio_sessions', schema=None) as batch_op:
        batch_op.alter_column('transcription_text',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_processing_status'))
        batch_op.drop_index(batch_op.f('idx_session_id'))
        batch_op.drop_index(batch_op.f('idx_user_id'))
        batch_op.create_index(batch_op.f('ix_audio_sessions_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_sessions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_sessions_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('metadata')

    with op.batch_alter_table('audio_transcriptions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_audio_session_id'))
        batch_op.create_index(batch_op.f('ix_audio_transcriptions_audio_session_id'), ['audio_session_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('upload_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_cycle'))
        batch_op.drop_index(batch_op.f('idx_processing_status'))
        batch_op.drop_index(batch_op.f('idx_upload_date'))
        batch_op.drop_index(batch_op.f('idx_user_id'))
        batch_op.create_index(batch_op.f('ix_documents_cycle'), ['cycle'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_upload_date'), ['upload_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('emotion_data', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_frame_number'))
        batch_op.drop_index(batch_op.f('idx_session_id'))
        batch_op.drop_index(batch_op.f('idx_timestamp'))
        batch_op.create_index(batch_op.f('ix_emotion_data_frame_number'), ['frame_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotion_data_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotion_data_timestamp_seconds'), ['timestamp_seconds'], unique=False)

    with op.batch_alter_table('generated_templates', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_report_id'))
        batch_op.drop_index(batch_op.f('idx_template_type'))
        batch_op.drop_index(batch_op.f('idx_user_id'))
        batch_op.create_index(batch_op.f('ix_generated_templates_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_templates_template_type'), ['template_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_templates_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_info', sa.JSON(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_created_at'))
        batch_op.drop_index(batch_op.f('idx_generation_status'))
        batch_op.drop_index(batch_op.f('idx_report_type'))
        batch_op.drop_index(batch_op.f('idx_user_id'))
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_generation_status'), ['generation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('metadata')

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_thesis_readiness'))
        batch_op.drop_index(batch_op.f('idx_user_id'))
        batch_op.drop_index(batch_op.f('user_id'))
        batch_op.create_index(batch_op.f('ix_student_profiles_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('text_analysis', schema=None) as batch_op:
        batch_op.alter_column('analysis_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_analysis_date'))
        batch_op.drop_index(batch_op.f('idx_document_id'))
        batch_op.drop_index(batch_op.f('idx_user_id'))
        batch_op.create_index(batch_op.f('ix_text_analysis_analysis_date'), ['analysis_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_analysis_document_id'), ['document_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_text_analysis_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('idx_email'))
        batch_op.drop_index(batch_op.f('idx_student_code'))
        batch_op.drop_index(batch_op.f('idx_username'))
        batch_op.drop_index(batch_op.f('student_code'))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_student_code'), ['student_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('video_sessions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_processing_status'))
        batch_op.drop_index(batch_op.f('idx_start_time'))
        batch_op.drop_index(batch_op.f('idx_user_id'))
        batch_op.drop_column('metadata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', mysql.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('idx_processing_status'), ['processing_status'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_student_code'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('student_code'), ['student_code'], unique=True)
        batch_op.create_index(batch_op.f('idx_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_student_code'), ['student_code'], unique=False)
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('text_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_analysis_user_id'))
        batch_op.drop_index(batch_op.f('ix_text_analysis_document_id'))
        batch_op.drop_index(batch_op.f('ix_text_analysis_analysis_date'))
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_analysis_date'), ['analysis_date'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('analysis_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_user_id'))
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_thesis_readiness'), ['thesis_readiness_score'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', mysql.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_reports_generation_status'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_generation_status'), ['generation_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('meta_info')

    with op.batch_alter_table('generated_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_templates_user_id'))
        batch_op.drop_index(batch_op.f('ix_generated_templates_template_type'))
        batch_op.drop_index(batch_op.f('ix_generated_templates_report_id'))
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_template_type'), ['template_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_report_id'), ['report_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('emotion_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emotion_data_timestamp_seconds'))
        batch_op.drop_index(batch_op.f('ix_emotion_data_session_id'))
        batch_op.drop_index(batch_op.f('ix_emotion_data_frame_number'))
        batch_op.create_index(batch_op.f('idx_timestamp'), ['timestamp_seconds'], unique=False)
        batch_op.create_index(batch_op.f('idx_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_frame_number'), ['frame_number'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_documents_upload_date'))
        batch_op.drop_index(batch_op.f('ix_documents_processing_status'))
        batch_op.drop_index(batch_op.f('ix_documents_cycle'))
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_upload_date'), ['upload_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('idx_cycle'), ['cycle'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('upload_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('audio_transcriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_transcriptions_audio_session_id'))
        batch_op.create_index(batch_op.f('idx_audio_session_id'), ['audio_session_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('audio_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', mysql.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_audio_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_audio_sessions_session_id'))
        batch_op.drop_index(batch_op.f('ix_audio_sessions_processing_status'))
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_processing_status'), ['processing_status'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('transcription_text',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    with op.batch_alter_table('attention_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attention_metrics_session_id'))
        batch_op.create_index(batch_op.f('idx_session_id'), ['session_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('ai_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_interactions_interaction_type'))
        batch_op.drop_index(batch_op.f('ix_ai_interactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_interactions_ai_service'))
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_interaction_type'), ['interaction_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_ai_service'), ['ai_service'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('response_text',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('prompt_text',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    op.create_table('system_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('log_level', mysql.ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'), nullable=False),
    sa.Column('module', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('function_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('stack_trace', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('request_method', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('request_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('metadata', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('system_logs_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('idx_log_level'), ['log_level'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
